name: Orlando backend

on:
  pull_request:
    branches:
      - release/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup vcpkg
        run: |
          cd backend
          git clone https://github.com/microsoft/vcpkg.git --depth=1
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install dependencies
        run: |
          cd backend
          ./vcpkg/vcpkg install

      - name: Configure CMake
        run: |
          cd backend
          cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build project
        run: |
          cd backend
          cmake --build build

      - name: Run tests
        run: |
          cd backend
          ctest --test-dir build --output-on-failure