name: Orlando backend

on:
  pull_request:
    branches:
      - release/**   # Маска для всех веток, начинающихся с release/
  push:
    branches:
      - master

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make script executable
        run: |
          cd backend
          chmod +x ./start.sh
          ./start.sh

      - name: Build tests
        run: |
          cd backend
          cmake -S . -B build
          cd build && cmake --build .